name: edu360
description: A new Flutter application.
authors: ['Mohamed Samir Abbas']
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.10+20

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  easy_localization: 2.3.2
  open_file: 3.0.1

  flutter_bloc: 4.0.0
  dio: 3.0.9
  file_picker: 1.10.0
  modal_progress_hud: 0.1.3
  flutter_svg:
  shared_preferences: 0.5.7+1

  chewie: 0.9.10
  video_player: 0.10.11+2
  fluttertoast: 4.0.0

  flutter_launcher_icons: 0.7.5
  image_picker: 0.6.7+6
  rxdart: 0.24.1
  firebase_auth: 0.18.0+1
  firebase_core : 0.5.0
  international_phone_input: 1.0.4
  flutter_cache_store: 0.7.2



  pdftron_flutter:
    git:
      url: git://github.com/PDFTron/pdftron-flutter.git


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/locales/
    - assets/images/
    - assets/images/flags/
    - assets/fonts/