name: edu360
description: A new Flutter application.
authors: ['Mohamed Samir Abbas']
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  easy_localization: 2.3.2
  flutter_bloc: 4.0.0
  dio: 3.0.9
  file_picker: 1.10.0
  modal_progress_hud: 0.1.3
  chewie: 0.9.10
  video_player: 0.10.11+2
  image_picker: 0.6.7+2
  fluttertoast: 4.0.0
  shared_preferences: 0.5.7+1
  flutter_svg:
  flutter_launcher_icons: 0.7.5
  rxdart: 0.24.1
  pdftron_flutter:
    git:
      url: git://github.com/PDFTron/pdftron-flutter.git


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/locales/
    - assets/images/
    - assets/images/flags/
    - assets/fonts/